name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/horizon
          ref: a0def8868993d33fb55374b3a309cde4b4640195 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/designate-dashboard
          ref: 4466de1a3bc97116940cd99df620fcd46b66a5c8 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/heat-dashboard
          ref: 825ef024401841c1078032111e82847582aee298 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/ironic-ui
          ref: 273780538b046eca1007bd5ea61b56ed52429a87 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/magnum-ui
          ref: 0a70f2f0a67f92977901d59b903c8f9319c9e2a7 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/manila-ui
          ref: 27022c83b1e7f3ad6ed3f4a1e4aeb4aab8e51d52 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/neutron-fwaas-dashboard
          ref: dac20874fff8960491d2f9268ad2dd574d5767a3 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/neutron-vpnaas-dashboard
          ref: a26073263b7e85a862f90a5d1e33f602a8db4ef3 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/octavia-dashboard
          ref: 848a2bb6d3db46c7f92f307bd6cb943be94bd1f1 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          image-name: horizon
          build-contexts: |
            horizon=openstack/horizon
            designate-dashboard=openstack/designate-dashboard
            heat-dashboard=openstack/heat-dashboard
            ironic-ui=openstack/ironic-ui
            magnum-ui=openstack/magnum-ui
            manila-ui=openstack/manila-ui
            neutron-fwaas-dashboard=openstack/neutron-fwaas-dashboard
            neutron-vpnaas-dashboard=openstack/neutron-vpnaas-dashboard
            octavia-dashboard=openstack/octavia-dashboard
          push: ${{ github.event_name != 'pull_request' }}
