name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/horizon
          ref: 039850556d0516e52b94b28f95762f310d779f16 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/designate-dashboard
          ref: 349f34baca5813aebde7097318cde160f60aa061 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/heat-dashboard
          ref: 04a8d01a0c02737c1990e7187db5f0f86e8cac93 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/ironic-ui
          ref: 8d03cdb78e800e74399744984bfccb7710557671 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/magnum-ui
          ref: 748b157dba5522c2c4392a8b92bc74309f103a2b # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/manila-ui
          ref: 4122678591b811ff9a5f28c26c6e60673623bc47 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/neutron-vpnaas-dashboard
          ref: d77ceeb44c741aac4d42a2152e18487557736752 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/octavia-dashboard
          ref: 7901a541e1b0278da945c57bc2e10a218e582c53 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          image-name: horizon
          build-contexts: |
            horizon=openstack/horizon
            designate-dashboard=openstack/designate-dashboard
            heat-dashboard=openstack/heat-dashboard
            ironic-ui=openstack/ironic-ui
            magnum-ui=openstack/magnum-ui
            manila-ui=openstack/manila-ui
            neutron-vpnaas-dashboard=openstack/neutron-vpnaas-dashboard
            octavia-dashboard=openstack/octavia-dashboard
          push: ${{ github.event_name != 'pull_request' }}
