name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/horizon
          ref: 6e92ad0994924cb8ccd11a82935ea377373cd491 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/designate-dashboard
          ref: 98a0a76eac11e94e2d6202f417ca8a616f259bac # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/heat-dashboard
          ref: c39223187e4215d309bf03aa36708242bda5d0da # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/ironic-ui
          ref: bce74adf2fd0969821fe21f3b31cfffe5214b59f # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/magnum-ui
          ref: 43698ccbd5e15b62ecd1ee29c409d6f2d98248b0 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/manila-ui
          ref: c1f5b0496b9f32e6431fe4ea96af70b8f7b52ab4 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/neutron-fwaas-dashboard
          ref: 87e941455ccb5e2b7c47f33e34ed2f4063c4987f # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/neutron-vpnaas-dashboard
          ref: a6c9ac148a073306d59af62c793d2e40d55dae1d # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          repository: openstack/octavia-dashboard
          ref: f9fde5ec2899cb20e1b218e16aabf9607d490688 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@e22141dfd5b75c4109fab95427441cfa762bc770 # main
        with:
          image-name: horizon
          build-contexts: |
            horizon=openstack/horizon
            designate-dashboard=openstack/designate-dashboard
            heat-dashboard=openstack/heat-dashboard
            ironic-ui=openstack/ironic-ui
            magnum-ui=openstack/magnum-ui
            manila-ui=openstack/manila-ui
            neutron-fwaas-dashboard=openstack/neutron-fwaas-dashboard
            neutron-vpnaas-dashboard=openstack/neutron-vpnaas-dashboard
            octavia-dashboard=openstack/octavia-dashboard
          push: ${{ github.event_name != 'pull_request' }}
